### ISSUE TITLE
Cppcheck does not work with the premium version

### ISSUE THREAD

**Issue by stevep682** [cppchecksolutions/cppcheclipse#9]
When I change the cppcheck exe to the premium version (C:\Program Files\Cppcheck Premium\cppcheck.exe), I get an error saying that 

>  Resource '/baremetal_template_app_am572x_a15/Cppcheck Premium' does not exist.

which does not match the actual path to cppcheck.exe. If I set the exe path to the open source version of Cppcheck, it works correctly.

> null
> com.googlecode.cppcheclipse.core
> Error
> Mon Sep 16 14:56:59 EDT 2024
> Error checking main.c
> 
> org.eclipse.core.runtime.CoreException: Could not run cppcheck
> 	at com.googlecode.cppcheclipse.ui.Builder$ResourceVisitor.runChecker(Builder.java:140)
> 	at com.googlecode.cppcheclipse.ui.Builder.processResource(Builder.java:309)
> 	at com.googlecode.cppcheclipse.ui.commands.RunCodeAnalysis$RunCodeAnalysisJob.runResource(RunCodeAnalysis.java:26)
> 	at com.googlecode.cppcheclipse.ui.commands.ResourceSelectionJob.run(ResourceSelectionJob.java:44)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: org.eclipse.core.internal.resources.ResourceException: Resource '/baremetal_template_app_am572x_a15/Cppcheck Premium' does not exist.
> 	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:330)
> 	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:204)
> 	at org.eclipse.core.internal.resources.Resource.findMarkers(Resource.java:989)
> 	at com.googlecode.cppcheclipse.ui.marker.ProblemReporter.reportProblem(ProblemReporter.java:68)
> 	at com.googlecode.cppcheclipse.ui.marker.ProblemReporter.reportProblem(ProblemReporter.java:54)
> 	at com.googlecode.cppcheclipse.core.ProblemProfile.reportProblems(ProblemProfile.java:180)
> 	at com.googlecode.cppcheclipse.core.Checker.reportProblems(Checker.java:120)
> 	at com.googlecode.cppcheclipse.core.command.CppcheckCommand.run(CppcheckCommand.java:294)
> 	at com.googlecode.cppcheclipse.core.Checker.run(Checker.java:109)
> 	at com.googlecode.cppcheclipse.ui.Builder$ResourceVisitor.runChecker(Builder.java:133)
> 	... 4 more
> Caused by: java.lang.Exception: Resource '/baremetal_template_app_am572x_a15/Cppcheck Premium' does not exist.
> 	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
> 	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
> 	... 14 more

**Comment by stevep682** [comment]
Upgraded Cppcheck and that fixed the issue
